version: 2.1

jobs: 
  build:
    docker: 
      - image: cimg/base:stable
    steps:
      -run : echo " build stage"
            

  test:
    docker:
      - image: cimg/base:stable
    steps:
      -run : echo " test stage" 



analyze:
  docker:
    - image: cimg/base:stable
  steps:
    - run : echo "anaylze stage"


workflows:
  my_workflows:
    jobs:
      - build 
      
      - test:
          requires:
            - build        
      - analyze:
          requires:
           - test
